-- This CLP file was created using DB2LOOK Version "11.1" 
-- Timestamp: Tue 23 Jul 2019 02:08:12 PM UTC
-- Database Name: BLUDB          
-- Database Manager Version: DB2/LINUXX8664 Version 11.1.9.0
-- Database Codepage: 1208
-- Database Collating Sequence is: IDENTITY
-- Alternate collating sequence(alt_collate): null
-- varchar2 compatibility(varchar2_compat): OFF


-- CONNECT TO BLUDB USER bluadmin;

------------------------------------------------
-- DDL Statements for Schemas
------------------------------------------------


CREATE DATABASE "BMGVZP";

CONNECT TO "BMGVZP";


------------------------------------------------
-- DDL Statements for Table "BMGVZP"."ORIGIN_SYSTEM_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."ORIGIN_SYSTEM_T"  (
		  "ORIG_SYSTEM_ID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "SYST_ABBREVIATION" CHAR(6 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "SYST_DESCRIPTION" VARCHAR(100 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "BILL_TYPE" VARCHAR(50 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "CLASSIFICATION_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "INVOICE_TYPE" VARCHAR(50 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "PORTAL_START_PAGE" INTEGER NOT NULL WITH DEFAULT ' ', 
		  "GBR_CLASS_CD" CHAR(1 OCTETS) , 
		  "GBR_REGION_CD" CHAR(3 OCTETS) , 
		  "PORTAL_API_NAME" CHAR(18 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "PORTAL_LINK" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "PAYMENT_ELIGABLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "IRV_MAN_LABEL" VARCHAR(50 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "IRV_BAN_LABEL" VARCHAR(50 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "GCP_ELIGIBILITY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT ' ', 
		  "CLAIM_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N', 
		  "VBE_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "BMGVZP"."ORIGIN_SYSTEM_T"

ALTER TABLE "BMGVZP"."ORIGIN_SYSTEM_T" 
	ADD CONSTRAINT "ORIG_SYSTEM_ID" PRIMARY KEY
		("ORIG_SYSTEM_ID")
	NOT ENFORCED;



-- DDL Statements for Indexes on Table "BMGVZP"."ORIGIN_SYSTEM_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."ORIGSYS1" ON "BMGVZP"."ORIGIN_SYSTEM_T" 
		("ORIG_SYSTEM_ID" ASC)
		CLUSTER 
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "BMGVZP"."ACCT_SUM_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."ACCT_SUM_T"  (
		  "MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MAN_BILL_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "BAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "ABAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STATE_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ORIG_SYSTEM_ID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VZ450_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "DEPT_CD" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAY_BY_DATE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TOT_BILL_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "PREV_BILL_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "TOT_PAYS" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "TOT_ADJS" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "TRNSFR_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "CURR_CHGS_MAN" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "TOT_BILL_CHGS_BANS" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "NET_PAST_DUE" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "LATE_PAY_CHGS" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "TOT_CURR_CHGS" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "PMTS_THRU_DATE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SUMM_BILL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_STATUS_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CLS_OF_SVC_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "HOLD_BILL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ARREARS_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LATE_PAY_CHG_RATE" DECIMAL(5,4) NOT NULL WITH DEFAULT  , 
		  "TAX_STATUS_IND_FD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TAX_STATUS_IND_ST" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TAX_STATUS_E911" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TAX_STATUS_SCHG" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TAX_STATUS_IND_LOC" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TAR_CD_INFO" CHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GEO_CD" CHAR(12 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_TYPE_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RESALE_DISC_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "PACKAGE_DISC_AMT" DECIMAL(9,2) NOT NULL WITH DEFAULT  , 
		  "ACCSUMXT_DAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_NAME" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ADDR_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "TAR_CD_INFO_ID" INTEGER , 
		  "TXFER_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TEXT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_PAGE_NUMBER" INTEGER NOT NULL WITH DEFAULT  , 
		  "ITEM_NUMBER" SMALLINT NOT NULL WITH DEFAULT  , 
		  "CUST_ID_CD" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CUST_ID_DEPT_CD" CHAR(15 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TOT_CARR_CHGS" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "COLL_REFER_AMT" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "BILL_BASIS_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "AMT_PEND_LEGAL" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "FUTURE_LPAY_RATE" DECIMAL(6,5) NOT NULL WITH DEFAULT  , 
		  "AMT_SUBJ_LPAY" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "PAYM_OPT_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PEND_LPAY_AMT" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "TOLL_CAP_AMT" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "CUSTOMER_PIN" CHAR(96 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TRANSFER_PAST_CHGS" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "RAO" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CLASSIFICATION_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NBBE_CODE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "COMPANY_CODE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "END_VZ450_SEQ_NBR" INTEGER , 
		  "CUST_ID_CD_ID" INTEGER , 
		  "CUST_ID_DEPT_CD_ID" INTEGER , 
		  "PAYMADDT_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "TEXT1_SEQ_NBR" INTEGER , 
		  "TEXT2_SEQ_NBR" INTEGER , 
		  "ADDL_TEXT_IND" CHAR(1 OCTETS) , 
		  "FIBER_ACCT_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SUB_CIC" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "COMP_SVC_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ISRT_CD" CHAR(8 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ISRT_STATION" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ISRT_WEIGHT" DECIMAL(5,4) NOT NULL WITH DEFAULT  , 
		  "CHK_DIGIT_NBR" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CHK_ACCEPT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_LINE_ID" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_ASSOC_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_SYSTEM_ID" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CLSSVC_USOC" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REV_BOOK_CD" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MERGE_FMT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SPEC_REC_ORIG_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ENTITY_CD" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CHANNEL_CD" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NATL_ACCT_ID" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LEGACY_ACCT_ID" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INV_BILL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICE_NBR" CHAR(25 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TEXT_KEY_NBR1" INTEGER NOT NULL WITH DEFAULT  , 
		  "TEXT_KEY_NBR2" INTEGER NOT NULL WITH DEFAULT  , 
		  "TEXT_KEY_NBR3" INTEGER NOT NULL WITH DEFAULT  , 
		  "IMMEDIATE_MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RECORD_LEVEL" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REMIT_ACCT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LDEP_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ORG_LEVEL1_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ORG_LEVEL2_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FREQUENCY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_CURR" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CONV_CURR" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REGION_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICE_SERIES_NBR" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "COST_CNTR_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WIRELESS_DAN" CHAR(16 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MASTER_CHANNEL_CD" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MODULE_084" CHAR(17 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPCO" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MODULE_087" VARCHAR(210 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SPEC_PROC_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WCAS_TAX_CAT" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VAMLOAD_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "MODULE_302" CHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SHIELDED_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Primary Key on Table "BMGVZP"."ACCT_SUM_T"

ALTER TABLE "BMGVZP"."ACCT_SUM_T" 
	ADD CONSTRAINT "ACCSUMX1" PRIMARY KEY
		("MAN",
		 "MAN_BILL_DATE",
		 "BAN",
		 "ABAN",
		 "BILL_DATE",
		 "ORIG_SYSTEM_ID",
		 "VZ450_SEQ_NBR")
	NOT ENFORCED;



-- DDL Statements for Indexes on Table "BMGVZP"."ACCT_SUM_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."ACCSUMX1" ON "BMGVZP"."ACCT_SUM_T" 
		("MAN" ASC,
		 "MAN_BILL_DATE" ASC,
		 "BAN" ASC,
		 "ABAN" ASC,
		 "BILL_DATE" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "VZ450_SEQ_NBR" ASC)
		CLUSTER 
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."ACCT_SUM_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."ACCSUMX2" ON "BMGVZP"."ACCT_SUM_T" 
		("BAN" ASC,
		 "BILL_DATE" ASC,
		 "MAN" ASC,
		 "MAN_BILL_DATE" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "ABAN" ASC,
		 "VZ450_SEQ_NBR" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."ACCT_SUM_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."ACCUDMX3" ON "BMGVZP"."ACCT_SUM_T" 
		("ORIG_SYSTEM_ID" ASC,
		 "MAN" ASC,
		 "BAN" ASC,
		 "BILL_DATE" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;



CREATE TABLE "BMGVZP"."MASTER_ACCT_NO_T"  (
		  "MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MAN_BILL_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "STAND_ALONE_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STATE_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VZ450_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "ORIG_SYSTEM_ID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "DB_SEGMENT_ID" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RAO" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CYCLE_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "CYCLE_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "CYCLE_ADJ_FACTOR" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VZ450_VERSION" SMALLINT NOT NULL WITH DEFAULT  , 
		  "VZ450_RELEASE" SMALLINT NOT NULL WITH DEFAULT  , 
		  "VZ450_VERS_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "TECH_SUPPT_NBR" CHAR(11 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LOB" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LOB_SUB_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VZ450_DSNAME" CHAR(44 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LOAD_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "PURGE_DATE" DATE , 
		  "LOCATION" CHAR(1 OCTETS) , 
		  "MAN_DAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_NAME" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ADDR_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "MAN_LINES" INTEGER NOT NULL WITH DEFAULT  , 
		  "BAN_COUNT" INTEGER NOT NULL WITH DEFAULT  , 
		  "ABAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FILE_SEQ_NBR" SMALLINT NOT NULL WITH DEFAULT  , 
		  "FILE_RERUN_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_SYSTEM_ID" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CONV_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MAN_PARTIAL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT 'N' , 
		  "INVOICE_NBR" CHAR(25 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_SYSTEM_ANNX" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICE_SERIES_NBR" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICE_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INTERNATIONAL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT  , 
		  "BILL_ACC_NUMBER" CHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_SYSTEM_CODE" CHAR(4 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REF_NUMBER" CHAR(16 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FINANCE_PERIOD" CHAR(6 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FINANCE_SUB_SEG" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RESOURCE_UBILL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PDF_LOAD_DATE" CHAR(26 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BIN_FILE_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "SHIELDED_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 






-- DDL Statements for Indexes on Table "BMGVZP"."MASTER_ACCT_NO_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."MASTACC1" ON "BMGVZP"."MASTER_ACCT_NO_T" 
		("MAN" ASC,
		 "MAN_BILL_DATE" ASC,
		 "ORIG_SYSTEM_ID" ASC)
		CLUSTER 
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."MASTER_ACCT_NO_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."MASTACC2" ON "BMGVZP"."MASTER_ACCT_NO_T" 
		("MAN_BILL_DATE" ASC,
		 "ORIG_SYSTEM_ID" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."MASTER_ACCT_NO_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."MASTACC3" ON "BMGVZP"."MASTER_ACCT_NO_T" 
		("ORIG_SYSTEM_ID" ASC,
		 "MAN_BILL_DATE" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."MASTER_ACCT_NO_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."MASTACC4" ON "BMGVZP"."MASTER_ACCT_NO_T" 
		("ABAN" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "BMGVZP"."OPCO_MASTER_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."OPCO_MASTER_T"  (
		  "OPCO" CHAR(5 OCTETS) NOT NULL , 
		  "GCP_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "COUNTRY_ID" SMALLINT NOT NULL WITH DEFAULT  , 
		  "OPCO_NAME" VARCHAR(250 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PORTAL_START_PAGE" INTEGER NOT NULL WITH DEFAULT  , 
		  "PORTAL_START_PAGE_MAN" INTEGER NOT NULL WITH DEFAULT  , 
		  "PORTAL_START_PAGE2" INTEGER NOT NULL WITH DEFAULT  , 
		  "PORTAL_START_PAGE2_MAN" INTEGER NOT NULL WITH DEFAULT  , 
		  "INVOICE_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "HOW_TO_PAY_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPERLESS_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAY_BY_MAIL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAY_CRED_RPT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INQUIRY_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "AUTO_CRED_CLM_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "E2EI_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GBR_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAYMENT_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NOTES" VARCHAR(500 OCTETS) NOT NULL WITH DEFAULT  , 
		  "UPDATED_BY" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "UPDATED_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT  , 
		  "REGION_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TAX_PAGE" INTEGER NOT NULL WITH DEFAULT  , 
		  "HOW2PAY_PAGE" INTEGER NOT NULL WITH DEFAULT  , 
		  "DEC_PREC_ZERO_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LATAM_RPT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ICI_ADJ_ELIGIBLE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "DOC_SUPPRESS" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CURRENCY_FMT" CHAR(18 OCTETS) NOT NULL WITH DEFAULT  , 
		  "N_CURRENCY_FMT" CHAR(18 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CURRENCY_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "DPZ_CURRENCY_FMT" CHAR(18 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICING_VLE" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 






-- DDL Statements for Indexes on Table "BMGVZP"."OPCO_MASTER_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."OPCOMST1" ON "BMGVZP"."OPCO_MASTER_T" 
		("OPCO" ASC)
		CLUSTER 
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;


CREATE TABLE "BMGVZP"."INVOICE_LIST_T"  (
		  "REPORT_ID_TS" CHAR(26 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_0_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_0_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_1_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_1_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_2_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_2_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_3_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_3_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_4_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_4_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_5_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_5_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_6_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_6_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MAN_BILL_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "ORIG_SYSTEM_ID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "ABAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "VZ450_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "ENTITY_CD" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PREV_BILL_AMT" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "TOT_PAYS" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "TOT_ADJS" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "NET_PAST_DUE" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "LATE_PAY_CHGS" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "TOT_CURR_CHGS" DECIMAL(13,2) NOT NULL WITH DEFAULT  , 
		  "PORTAL_START_PAGE" INTEGER NOT NULL WITH DEFAULT  , 
		  "DISP_ACCT_NUM" CHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CUST_ACCT_NUM" CHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "WTN" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "MAN_PARTIAL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "RECENT_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "LAST_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "BAN_LVL" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ENTERPRISE_ID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "SB_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "SP_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "SERVICE_TYPE" CHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SP_STATUS" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SP_STATUS_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "SP_BACKEND_SYSTEM" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CHANNEL_CD" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LOGIN_ID" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICE_NBR" CHAR(25 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REMIT_ACCT_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CURRENCY_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REGION_CD" CHAR(3 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INVOICE_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INTERNATIONAL_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_NAME" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ADDR_SEQ_NBR" INTEGER NOT NULL WITH DEFAULT  , 
		  "ADDR_CITY" VARCHAR(60 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ADDR_STATE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GBR" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GBR_OSID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GBR_DATE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPER_SUPP_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPER_ELIG_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPER_CONTR_AMEND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ZIP_CD" CHAR(9 OCTETS) NOT NULL WITH DEFAULT  , 
		  "TOT_BILL_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "VERIFIED" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PEND_PAY_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "PEND_ADJ_AMT" DECIMAL(11,2) NOT NULL WITH DEFAULT  , 
		  "BILL_ADDRESS" VARCHAR(180 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SVC_ADDRESS" VARCHAR(180 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CREF" CHAR(15 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STAND_ALONE_IND" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_PERIOD" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPER_CHARGE_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPER_CALL_DETAIL" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAPER_OID_STATUS" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_ALIAS" VARCHAR(250 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GBR_CLASS_CD" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "GBR_SP_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "GBR_SB_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "GBR_SERVICE_TYPE" CHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "M077_SUPP_DATA_ID" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FREQUENCY" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPCO" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCT_IN_GCP" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CORP_IN_GCP" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_7_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_7_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_8_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_8_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_9_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_9_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "LVL_10_TYPE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LVL_10_OID" DECIMAL(10,0) NOT NULL WITH DEFAULT  , 
		  "STATE_CODE" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LAST_ONLINE_ACTION" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "INQUIRY_PENDING" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "DISP_MAN" CHAR(20 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCOUNT_TYPE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STRUCTURE_ID" INTEGER NOT NULL WITH DEFAULT  , 
		  "LINE_NUM" INTEGER NOT NULL WITH DEFAULT  , 
		  "Q2C_FLAG" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		  IN "USERSPACE1"
		 ORGANIZE BY ROW; 



-- DDL Statements for Indexes on Table "BMGVZP"."INVOICE_LIST_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."INVLISN1" ON "BMGVZP"."INVOICE_LIST_T" 
		("REPORT_ID_TS" ASC,
		 "LVL_0_TYPE" ASC,
		 "LVL_0_OID" ASC,
		 "LVL_1_TYPE" ASC,
		 "LVL_1_OID" ASC,
		 "LVL_2_TYPE" ASC,
		 "LVL_2_OID" ASC,
		 "LVL_3_TYPE" ASC,
		 "LVL_3_OID" ASC,
		 "LVL_4_TYPE" ASC,
		 "LVL_4_OID" ASC,
		 "LVL_5_TYPE" ASC,
		 "LVL_5_OID" ASC,
		 "LVL_6_TYPE" ASC,
		 "LVL_6_OID" ASC,
		 "ABAN" ASC)
		CLUSTER 
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."INVOICE_LIST_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."INVLISN2" ON "BMGVZP"."INVOICE_LIST_T" 
		("MAN" ASC,
		 "MAN_BILL_DATE" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "BAN" ASC,
		 "BILL_DATE" ASC,
		 "ABAN" ASC)
		PARTITIONED
		PCTFREE 0 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."INVOICE_LIST_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."INVLISN3" ON "BMGVZP"."INVOICE_LIST_T" 
		("STRUCTURE_ID" ASC,
		 "LINE_NUM" ASC)
		PARTITIONED
		
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."INVOICE_LIST_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."INVLISN4" ON "BMGVZP"."INVOICE_LIST_T" 
		("REPORT_ID_TS" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "MAN" ASC,
		 "MAN_BILL_DATE" ASC,
		 "BAN" ASC,
		 "ABAN" ASC,
		 "WTN" ASC)
		PARTITIONED
		PCTFREE 0 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "BMGVZP"."PAYMENT_INELIGIBLE_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."PAYMENT_INELIGIBLE_T"  (
		  "MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ORIG_SYSTEM_ID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "PAYMENT_TYPE" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACCOUNT_NUMBER" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "SOURCE_SYSTEM" VARCHAR(50 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ALT_ACCOUNT_NUMBER" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "CARMS_SHORT_NAME" VARCHAR(200 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LAST_UPD_TIMESTAMP" TIMESTAMP NOT NULL WITH DEFAULT  )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 






-- DDL Statements for Indexes on Table "BMGVZP"."PAYMENT_INELIGIBLE_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."INELIGU1" ON "BMGVZP"."PAYMENT_INELIGIBLE_T" 
		("MAN" ASC,
		 "BAN" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "ACCOUNT_NUMBER" ASC)
		PCTFREE 10 
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "BMGVZP"."SHIELD_XREF_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."SHIELD_XREF_T"  (
		  "NEW_SYS_MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "NEW_SYS_BAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LEG_MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LEG_BAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "LEG_OSID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "FIRST_BILL_DATE" DATE NOT NULL WITH DEFAULT  , 
		  "LAST_BILL_DATE" DATE NOT NULL WITH DEFAULT  )   
		 COMPRESS YES STATIC  
		 CCSID UNICODE  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 






-- DDL Statements for Indexes on Table "BMGVZP"."SHIELD_XREF_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."SHIELDX2" ON "BMGVZP"."SHIELD_XREF_T" 
		("LEG_MAN" ASC,
		 "LEG_BAN" ASC,
		 "LEG_OSID" ASC)
		PCTFREE 10 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."SHIELD_XREF_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."SHILEDX1" ON "BMGVZP"."SHIELD_XREF_T" 
		("NEW_SYS_MAN" ASC,
		 "NEW_SYS_BAN" ASC,
		 "LEG_MAN" ASC,
		 "LEG_BAN" ASC,
		 "LEG_OSID" ASC)
		PCTFREE 10 CLUSTER 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;




------------------------------------------------
-- DDL Statements for Table "BMGVZP"."CURRENT_BAN_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."CURRENT_BAN_T"  (
		  "BAN" CHAR(13 OCTETS) NOT NULL , 
		  "ORIG_SYSTEM_ID" CHAR(2 OCTETS) NOT NULL , 
		  "MAN" CHAR(13 OCTETS) NOT NULL , 
		  "FIRST_DATE" DATE NOT NULL , 
		  "LAST_DATE" DATE NOT NULL , 
		  "TOT_BILL_AMT" DECIMAL(11,2) NOT NULL , 
		  "TOT_CURR_CHGS" DECIMAL(11,2) NOT NULL , 
		  "NET_PAST_DUE" DECIMAL(11,2) NOT NULL , 
		  "TIMESTAMP" CHAR(26 OCTETS) NOT NULL , 
		  "ENTITY_CD" CHAR(5 OCTETS) NOT NULL , 
		  "PREV_BILL_AMT" DECIMAL(13,2) NOT NULL , 
		  "TOT_PAYS" DECIMAL(13,2) NOT NULL , 
		  "TOT_ADJS" DECIMAL(13,2) NOT NULL , 
		  "LATE_PAY_CHGS" DECIMAL(13,2) NOT NULL , 
		  "DISP_ACCT_NUM" CHAR(20 OCTETS) NOT NULL , 
		  "MAN_PARTIAL_IND" CHAR(1 OCTETS) NOT NULL , 
		  "ENTERPRISE_ID" DECIMAL(10,0) NOT NULL , 
		  "SB_OID" DECIMAL(10,0) NOT NULL , 
		  "SP_OID" DECIMAL(10,0) NOT NULL , 
		  "SERVICE_TYPE" CHAR(20 OCTETS) NOT NULL , 
		  "SP_STATUS" CHAR(1 OCTETS) NOT NULL , 
		  "SP_STATUS_DATE" CHAR(10 OCTETS) NOT NULL , 
		  "SP_BACKEND_SYSTEM" CHAR(10 OCTETS) NOT NULL , 
		  "INVOICE_NBR" CHAR(25 OCTETS) NOT NULL , 
		  "CHANNEL_CD" CHAR(2 OCTETS) NOT NULL , 
		  "REMIT_ACCT_IND" CHAR(1 OCTETS) NOT NULL , 
		  "CURRENCY_CD" CHAR(3 OCTETS) NOT NULL , 
		  "REGION_CD" CHAR(3 OCTETS) NOT NULL , 
		  "INVOICE_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "INTERNATIONAL_IND" CHAR(1 OCTETS) NOT NULL , 
		  "ACCT_NAME" CHAR(30 OCTETS) NOT NULL , 
		  "ADDR_SEQ_NBR" INTEGER NOT NULL , 
		  "ADDR_CITY" VARCHAR(60 OCTETS) NOT NULL , 
		  "ADDR_STATE" CHAR(2 OCTETS) NOT NULL , 
		  "GBR" CHAR(13 OCTETS) NOT NULL , 
		  "GBR_OSID" CHAR(2 OCTETS) NOT NULL , 
		  "GBR_DATE" CHAR(10 OCTETS) NOT NULL , 
		  "PAPER_SUPP_IND" CHAR(1 OCTETS) NOT NULL , 
		  "PAPER_ELIG_IND" CHAR(1 OCTETS) NOT NULL , 
		  "PAPER_CONTR_AMEND" CHAR(1 OCTETS) NOT NULL , 
		  "ZIP_CD" CHAR(9 OCTETS) NOT NULL , 
		  "PEND_ADJ_AMT" DECIMAL(11,2) NOT NULL , 
		  "PEND_PAY_AMT" DECIMAL(11,2) NOT NULL , 
		  "BILL_ADDRESS" VARCHAR(180 OCTETS) NOT NULL , 
		  "SVC_ADDRESS" VARCHAR(180 OCTETS) NOT NULL , 
		  "CREF" CHAR(15 OCTETS) NOT NULL , 
		  "STAND_ALONE_IND" CHAR(1 OCTETS) NOT NULL , 
		  "BILL_PERIOD" CHAR(2 OCTETS) NOT NULL , 
		  "PAPER_CHARGE_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "PAPER_CALL_DETAIL" CHAR(2 OCTETS) NOT NULL , 
		  "PAPER_OID_STATUS" CHAR(2 OCTETS) NOT NULL , 
		  "ACCT_ALIAS" VARCHAR(250 OCTETS) NOT NULL , 
		  "GBR_CLASS_CD" CHAR(1 OCTETS) NOT NULL , 
		  "GBR_SP_OID" DECIMAL(10,0) NOT NULL , 
		  "GBR_SB_OID" DECIMAL(10,0) NOT NULL , 
		  "GBR_SERVICE_TYPE" CHAR(20 OCTETS) NOT NULL , 
		  "M077_SUPP_DATA_ID" CHAR(30 OCTETS) NOT NULL , 
		  "FREQUENCY" CHAR(1 OCTETS) NOT NULL , 
		  "PENDING_LAST_DATE" CHAR(10 OCTETS) NOT NULL , 
		  "OPCO" CHAR(5 OCTETS) NOT NULL , 
		  "ACCT_IN_GCP" CHAR(1 OCTETS) NOT NULL , 
		  "CORP_IN_GCP" CHAR(1 OCTETS) NOT NULL , 
		  "STATE_CODE" CHAR(2 OCTETS) NOT NULL , 
		  "LAST_ONLINE_ACTION" CHAR(1 OCTETS) NOT NULL , 
		  "INQUIRY_PENDING" CHAR(1 OCTETS) NOT NULL , 
		  "MAN_DAN" CHAR(20 OCTETS) NOT NULL , 
		  "LAST_BILL_DATE" DATE NOT NULL , 
		  "MAN_SP_OID" DECIMAL(10,0) NOT NULL , 
		  "RAO" CHAR(3 OCTETS) NOT NULL , 
		  "COMP_SVC_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "SUMM_BILL_IND" CHAR(1 OCTETS) NOT NULL , 
		  "TAX_STATUS_IND_FD" CHAR(1 OCTETS) NOT NULL , 
		  "TAX_STATUS_IND_ST" CHAR(1 OCTETS) NOT NULL , 
		  "TAX_STATUS_E911" CHAR(1 OCTETS) NOT NULL , 
		  "TAX_STATUS_SCHG" CHAR(1 OCTETS) NOT NULL , 
		  "TAX_STATUS_IND_LOC" CHAR(1 OCTETS) NOT NULL , 
		  "CLS_OF_SVC_TYPE" CHAR(1 OCTETS) NOT NULL , 
		  "ACCT_TYPE_CD" CHAR(1 OCTETS) NOT NULL , 
		  "PAYM_OPT_CD" CHAR(1 OCTETS) NOT NULL , 
		  "SPEC_PROC_CD" CHAR(1 OCTETS) NOT NULL , 
		  "WCAS_TAX_CAT" CHAR(2 OCTETS) NOT NULL , 
		  "AR_SYSTEM" CHAR(30 OCTETS) NOT NULL , 
		  "Q2C_FLAG" CHAR(1 OCTETS) NOT NULL , 
		  "ACCOUNT_TYPE" CHAR(10 OCTETS) NOT NULL , 
		  "CONF_IND" CHAR(1 OCTETS) NOT NULL , 
		  "SUB_CONTRACT_ID" CHAR(3 OCTETS) NOT NULL , 
		  "SHIELDED_IND" CHAR(1 OCTETS) NOT NULL )   
		 COMPRESS YES STATIC  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 






-- DDL Statements for Indexes on Table "BMGVZP"."CURRENT_BAN_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."CURRBAN1" ON "BMGVZP"."CURRENT_BAN_T" 
		("BAN" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "MAN" ASC,
		 "TIMESTAMP" ASC)
		PCTFREE 0 CLUSTER 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."CURRENT_BAN_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."CURRBAN2" ON "BMGVZP"."CURRENT_BAN_T" 
		("MAN" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "BAN" ASC)
		PCTFREE 0 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."CURRENT_BAN_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."CURRBAN3" ON "BMGVZP"."CURRENT_BAN_T" 
		("OPCO" ASC,
		 "ORIG_SYSTEM_ID" ASC,
		 "MAN" ASC,
		 "BAN" ASC)
		PCTFREE 0 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "BMGVZP"."CURRENT_BAN_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE INDEX "BMGVZP"."CURRBAN4" ON "BMGVZP"."CURRENT_BAN_T" 
		("SP_OID" ASC)
		PCTFREE 0 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "BMGVZP"."COLUMBIA_STATUS_T"
------------------------------------------------
 

CREATE TABLE "BMGVZP"."COLUMBIA_STATUS_T"  (
		  "MAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OSID" CHAR(2 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BAN" CHAR(13 OCTETS) NOT NULL WITH DEFAULT  , 
		  "BILL_DATE" DATE NOT NULL WITH DEFAULT '0001-01-01' , 
		  "INVOICE_NBR" CHAR(25 OCTETS) NOT NULL WITH DEFAULT  , 
		  "OPCO" CHAR(5 OCTETS) NOT NULL WITH DEFAULT  , 
		  "STATUS" CHAR(1 OCTETS) NOT NULL WITH DEFAULT  , 
		  "DUE_BY_DATE" CHAR(10 OCTETS) NOT NULL WITH DEFAULT '0001-01-01' , 
		  "MAN_LOAD_TS" CHAR(26 OCTETS) NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000' , 
		  "XML_LOAD_TS" CHAR(26 OCTETS) NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000' , 
		  "UPDATED_TS" CHAR(26 OCTETS) NOT NULL WITH DEFAULT '0001-01-01-00.00.00.000000' , 
		  "ACTIONED_BY_USERID" CHAR(30 OCTETS) NOT NULL WITH DEFAULT  , 
		  "ACTIONED_BY_NAME" VARCHAR(250 OCTETS) NOT NULL WITH DEFAULT  , 
		  "REASON_TEXT" VARCHAR(1000 OCTETS) )   
		 COMPRESS YES STATIC  
		 IN "USERSPACE1"  
		 ORGANIZE BY ROW; 


-- DDL Statements for Indexes on Table "BMGVZP"."COLUMBIA_STATUS_T"

SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

CREATE UNIQUE INDEX "BMGVZP"."CLMSTATX" ON "BMGVZP"."COLUMBIA_STATUS_T" 
		("MAN" ASC,
		 "OSID" ASC,
		 "BAN" ASC,
		 "BILL_DATE" ASC,
		 "INVOICE_NBR" ASC)
		CLUSTER 
		COMPRESS NO 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;


-- ---------------------------------
-- -- DDL Statements for Stored Procedures
-- ---------------------------------


-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."VOIPPROC" 
-- 		( 
-- 		IN      CLE1   CHARACTER(10 OCTETS),
-- 		OUT     BAN   CHARACTER(13 OCTETS),
-- 		OUT     MAN   CHARACTER(13 OCTETS),
-- 		OUT     ORIG_SYSTEM_ID   CHARACTER(2 OCTETS),
-- 		OUT     MAN_BILL_DATE   CHARACTER(10 OCTETS),
-- 		OUT     BILL_DATE   CHARACTER(10 OCTETS),
-- 		OUT     ABAN   CHARACTER(13 OCTETS),
-- 		OUT     INVOICE   CHARACTER(23 OCTETS),
-- 		OUT     UOM   CHARACTER(13 OCTETS),
-- 		OUT     AMOUNT   DECIMAL(12, 3),
-- 		OUT     DISC_PROMOS   DECIMAL(12, 3),
-- 		OUT     TAXES_SURCHGS   DECIMAL(12, 3),
-- 		OUT     GST_HST_AMT   DECIMAL(12, 3),
-- 		OUT     PST_QST_AMT   DECIMAL(12, 3),
-- 		OUT     TOTAL_CHGS   DECIMAL(12, 3),
-- 		OUT     SERVICE_ID   CHARACTER(23 OCTETS),
-- 		OUT     INSTANCE_ID   CHARACTER(23 OCTETS),
-- 		OUT     LOCATION_ADDR   CHARACTER(23 OCTETS),
-- 		OUT     CONTRACT_SOF   CHARACTER(23 OCTETS),
-- 		OUT     CALLS   CHARACTER(23 OCTETS),
-- 		OUT     MINS   DECIMAL(12, 3),
-- 		OUT     DESTINATION   CHARACTER(23 OCTETS)
-- 		)
-- 		DYNAMIC RESULT SETS 0 
-- 		SPECIFIC SQL190411130448057 
-- 		EXTERNAL NAME 'voip!reports()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		NOT DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."VOIPPROC" 
-- 		( 
-- 		IN      CLE1   CHARACTER(10 OCTETS)
-- 		)
-- 		DYNAMIC RESULT SETS 1 
-- 		SPECIFIC SQL190412101518358 
-- 		EXTERNAL NAME 'voip!reports()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		NOT DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."TEST_JAVAPROC" 
-- 		( 
-- 		IN      OPCONAME   CHARACTER(50 OCTETS),
-- 		IN      OPCO   CHARACTER(5 OCTETS),
-- 		OUT     COUNT3   INTEGER
-- 		)
-- 		DYNAMIC RESULT SETS 0 
-- 		SPECIFIC SQL190624082237352 
-- 		EXTERNAL NAME 'Testjavasp!testProc()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		NOT DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';
-- SET CURRENT SCHEMA = "BMGVZP";
-- SET CURRENT PATH = "SYSIBM","SYSFUN","SYSPROC","SYSIBMADM","BLUADMIN";

-- CREATE PROCEDURE P3( IN P1 char(10), OUT P2 char(25))     
--      LANGUAGE SQL
--    BEGIN
--        SELECT OPCO_NAME INTO P2 FROM OPCO_MASTER_T WHERE OPCO=P1;--
--    END;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."JAVAPROC" 
-- 		(
-- 		)
-- 		DYNAMIC RESULT SETS 0 
-- 		SPECIFIC INSERT 
-- 		EXTERNAL NAME 'Testjavasp!testjavasp()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."JAVAPROC1" 
-- 		(
-- 		)
-- 		DYNAMIC RESULT SETS 0 
-- 		SPECIFIC SQL190626115032966 
-- 		EXTERNAL NAME 'Testjavasp!testjavasp1()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."JAVAPROC2" 
-- 		(
-- 		)
-- 		DYNAMIC RESULT SETS 0 
-- 		SPECIFIC SQL190626122110967 
-- 		EXTERNAL NAME 'Testjavasp!testjavasp1()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

-- SET SYSIBM.NLS_STRING_UNITS = 'SYSTEM';

-- CREATE PROCEDURE "BMGVZP"."UPDATE_JAVASP" 
-- 		( 
-- 		IN      INPUT   CHARACTER(5 OCTETS)
-- 		)
-- 		DYNAMIC RESULT SETS 0 
-- 		SPECIFIC UPDATE 
-- 		EXTERNAL NAME 'UPDATE_JAVASP!uPDATE_JAVASP()' 
-- 		LANGUAGE JAVA     
-- 		PARAMETER STYLE JAVA     
-- 		DETERMINISTIC 
-- 		FENCED THREADSAFE 
-- 		MODIFIES SQL DATA 
-- 		NO DBINFO;

COMMIT WORK;

CONNECT RESET;

TERMINATE;

